use std::fmt::Write as _;

use super::shell::{iso_label, menu_title, sh_quote, sh_words};
use super::{bootloader, dedup, enabled_services, ignored_packages, init, install_packages, repos};
use crate::profile::validate::{firmware_owners, ValidProfile};
use crate::profile::{Bootloader, Init, Profile};

/// Fixed names inside the output folder; `output::save_output` copies them there.
pub const OVERLAY_DIR: &str = "overlay";
pub const HOOK_PATH: &str = "hooks/post_rootfs.sh";

const HELPERS: &str = r#"info() { printf '==> %s\n' "$*"; }
warn() { printf '!! %s\n' "$*" >&2; }
die() { warn "$*"; exit 1; }

# A private /dev (tmpfs + nodes), not a bind of the host's: a package trigger
# recreating /dev/null through a bind mount corrupts the host's /dev/null.
mount_chroot() {
	mkdir -p "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/dev"
	mount --bind /proc "$ROOTFS/proc"
	mount --bind /sys "$ROOTFS/sys"
	mount -t tmpfs -o mode=755,nosuid tmpfs "$ROOTFS/dev"
	mkdir -p "$ROOTFS/dev/pts" "$ROOTFS/dev/shm"
	mknod -m 666 "$ROOTFS/dev/null" c 1 3
	mknod -m 666 "$ROOTFS/dev/zero" c 1 5
	mknod -m 666 "$ROOTFS/dev/full" c 1 7
	mknod -m 666 "$ROOTFS/dev/random" c 1 8
	mknod -m 666 "$ROOTFS/dev/urandom" c 1 9
	mknod -m 666 "$ROOTFS/dev/tty" c 5 0
	mknod -m 666 "$ROOTFS/dev/ptmx" c 5 2
	mount -t devpts -o gid=5,mode=620 devpts "$ROOTFS/dev/pts"
	mount -t tmpfs -o mode=1777 tmpfs "$ROOTFS/dev/shm"
}
umount_chroot() {
	local m
	for m in dev/shm dev/pts dev sys proc; do
		if mountpoint -q "$ROOTFS/$m" 2>/dev/null; then
			umount "$ROOTFS/$m" || umount -l "$ROOTFS/$m"
		fi
	done
	return 0
}
trap umount_chroot EXIT
"#;

pub fn generate_with(v: &ValidProfile, voidlab_repo: &str) -> String {
    let p = v.get();
    let fw = firmware_owners(p);
    // Bootloaders that own a firmware path, in list order, with their roles.
    let active: Vec<(Bootloader, bool, bool)> = p
        .bootloaders
        .iter()
        .map(|b| (*b, fw.bios == Some(*b), fw.uefi == Some(*b)))
        .filter(|(_, bios, uefi)| *bios || *uefi)
        .collect();
    let label = iso_label(&p.name);
    let dracut = init::uses_dracut(p.init);

    let mut s = String::new();
    header(&mut s, p, &active, &label);
    s.push_str(HELPERS);
    let needs_efi_image = active.iter().any(|(b, _, uefi)| *uefi && matches!(b, Bootloader::Grub | Bootloader::Refind));
    if needs_efi_image {
        s.push_str(bootloader::EFI_IMAGE_FN);
    }

    section(&mut s, 1, "preflight", "host tools for the chosen init and bootloaders");
    preflight(&mut s, p, &active);

    section(&mut s, 2, "repositories", "custom, then presets, then official");
    s.push_str("REPO_ARGS=(\n");
    for r in repos::repo_list_with(p, voidlab_repo) {
        let _ = writeln!(s, "\t--repository={}", sh_quote(&r));
    }
    s.push_str(")\n");

    section(&mut s, 3, "rootfs", &format!("init {}, userland {}", p.init.id(), p.userland.id()));
    rootfs(&mut s, p);

    section(&mut s, 4, "configure", "overlay, identity, services, hook");
    configure(&mut s, p);

    section(&mut s, 5, "kernel + initramfs", if dracut { "dracut + vmklive" } else { "dynamod-init" });
    s.push_str(
        r#"KVER="$(ls "$ROOTFS/usr/lib/modules" | sort -V | tail -1)"
[ -n "$KVER" ] || die "no kernel installed in the rootfs"
cp "$ROOTFS/boot/vmlinuz-$KVER" "$ISODIR/boot/vmlinuz"
"#,
    );
    s.push_str(init::initramfs_stage(p.init));

    section(&mut s, 6, "squashfs", if dracut { "dmsquash-live layout" } else { "dynamod live layout" });
    s.push_str("rm -f \"$ROOTFS/etc/resolv.conf\"\numount_chroot\n");
    s.push_str(init::squashfs_stage(p.init));

    section(&mut s, 7, "bootloaders", &active_summary(&active));
    let cmdline = init::cmdline(p, &label);
    let _ = writeln!(s, "CMDLINE={}", sh_quote(&cmdline));
    let ram = if dracut { format!("{cmdline} rd.live.ram") } else { String::new() };
    let _ = writeln!(s, "CMDLINE_RAM={}", sh_quote(&ram));
    for (b, bios, uefi) in &active {
        s.push_str(&bootloader::stage(*b, *bios, *uefi));
    }

    section(&mut s, 8, "iso", "hybrid El Torito image");
    iso(&mut s, &active);
    s
}

fn header(s: &mut String, p: &Profile, active: &[(Bootloader, bool, bool)], label: &str) {
    let desktops = if p.desktops.is_empty() {
        "none (console)".to_string()
    } else {
        p.desktops.iter().map(|d| d.id()).collect::<Vec<_>>().join(", ")
    };
    s.push_str("#!/bin/bash\n");
    let _ = writeln!(s, "# Generated by vessel from profile {:?}. Edit the profile in vessel, not this file.", p.name);
    let _ = writeln!(s, "#   init: {}   userland: {}", p.init.id(), p.userland.id());
    let _ = writeln!(s, "#   bootloaders: {}", active_summary(active));
    let _ = writeln!(s, "#   desktops: {desktops}   display manager: {}", p.display_manager.id());
    let _ = writeln!(s, "# Run as root. WORK and OUT may be overridden from the environment.");
    s.push_str("set -euo pipefail\n\n");
    s.push_str("HERE=\"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")\" && pwd)\"\n");
    s.push_str("WORK=\"${WORK:-$HERE/work}\"\nROOTFS=\"$WORK/rootfs\"\nISODIR=\"$WORK/iso\"\nOUT=\"${OUT:-$HERE/out}\"\n");
    let _ = writeln!(s, "ARCH={}", sh_quote(&p.arch));
    let _ = writeln!(s, "ISO_NAME={}", sh_quote(&p.name));
    let _ = writeln!(s, "LABEL={}", sh_quote(label));
    let _ = writeln!(s, "MENU_TITLE={}", sh_quote(&menu_title(&p.name)));
    let _ = writeln!(s, "LIVE_USER={}", sh_quote(&p.live.user));
    let _ = writeln!(s, "LIVE_HOSTNAME={}", sh_quote(&p.live.hostname));
    let _ = writeln!(s, "LIVE_LOCALE={}", sh_quote(&p.live.locale));
    let _ = writeln!(s, "LIVE_KEYMAP={}", sh_quote(&p.live.keymap));
    let _ = writeln!(s, "LIVE_TIMEZONE={}", sh_quote(&p.live.timezone));
    let _ = writeln!(s, "ISO=\"$OUT/{}-$(date +%Y%m%d).iso\"\n", label.to_ascii_lowercase());
}

fn section(s: &mut String, n: u8, name: &str, why: &str) {
    let _ = writeln!(s, "\n# --- {n}. {name}: {why} ---");
}

fn active_summary(active: &[(Bootloader, bool, bool)]) -> String {
    active
        .iter()
        .map(|(b, bios, uefi)| {
            let roles = match (bios, uefi) {
                (true, true) => "BIOS+UEFI",
                (true, false) => "BIOS",
                _ => "UEFI",
            };
            format!("{} ({roles})", b.id())
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn preflight(s: &mut String, p: &Profile, active: &[(Bootloader, bool, bool)]) {
    s.push_str(
        r#"[ "$(id -u)" -eq 0 ] || die "run as root (chroot, mounts, mknod)"
missing=0
need() { command -v "$1" >/dev/null 2>&1 || { warn "missing host tool $1 (xbps-install -S $2)"; missing=1; }; }
need_file() { [ -e "$1" ] || { warn "missing host file $1 (xbps-install -S $2)"; missing=1; }; }
"#,
    );
    let mut tools: Vec<(&str, &str)> = vec![
        ("xbps-install", "xbps"),
        ("mksquashfs", "squashfs-tools"),
        ("xorriso", "xorriso"),
        ("mountpoint", "util-linux"),
    ];
    if init::uses_dracut(p.init) {
        tools.push(("mkfs.ext3", "e2fsprogs"));
    } else {
        tools.extend([("readelf", "binutils"), ("cpio", "cpio"), ("gzip", "gzip"), ("modprobe", "kmod"), ("depmod", "kmod")]);
    }
    let mut files = Vec::new();
    for (b, bios, uefi) in active {
        tools.extend(bootloader::host_tools(*b, *bios, *uefi));
        files.extend(bootloader::host_files(*b, *bios, *uefi));
    }
    let mut seen = Vec::new();
    for (cmd, pkg) in tools {
        if !seen.contains(&cmd) {
            seen.push(cmd);
            let _ = writeln!(s, "need {cmd} {pkg}");
        }
    }
    for (file, pkg) in files {
        let _ = writeln!(s, "need_file {file} {pkg}");
    }
    s.push_str(
        r#"[ "$missing" -eq 0 ] || die "install the missing host packages and re-run"
free_gb=$(df --output=avail -BG "$HERE" | tail -1 | tr -dc 0-9)
[ "${free_gb:-0}" -ge 10 ] || die "need at least 10 GiB free under $HERE (have ${free_gb:-0} GiB)"
"#,
    );
}

fn rootfs(s: &mut String, p: &Profile) {
    s.push_str(
        r#"case "$WORK" in
	"" | / | /home | /root | "$HERE") die "refusing to use WORK=$WORK as the scratch directory" ;;
esac
umount_chroot
if grep -qF " $WORK/" /proc/mounts; then
	die "something is still mounted under $WORK; unmount it before rebuilding"
fi
rm -rf "$WORK"
mkdir -p "$ROOTFS/var/db/xbps/keys" "$ROOTFS/etc/xbps.d" "$ISODIR/boot" "$OUT"
cp -a /var/db/xbps/keys/. "$ROOTFS/var/db/xbps/keys/"
"#,
    );
    let ignored = ignored_packages(p);
    if !ignored.is_empty() {
        s.push_str("cat > \"$ROOTFS/etc/xbps.d/00-vessel.conf\" <<'VESSEL_IGNORE'\n");
        for pkg in &ignored {
            let _ = writeln!(s, "ignorepkg={pkg}");
        }
        s.push_str("VESSEL_IGNORE\n");
    }
    // dynamod-logind and elogind ship the same login1 D-Bus policy file.
    let force = if p.init == Init::Dynamod { " -I" } else { "" };
    let _ = writeln!(s, "info \"Installing {} packages into $ROOTFS\"", install_packages(p).len());
    let _ = writeln!(
        s,
        "XBPS_ARCH=\"$ARCH\" xbps-install -S -y{force} -r \"$ROOTFS\" -C \"$ROOTFS/etc/xbps.d\" \"${{REPO_ARGS[@]}}\" \\\n\t{}",
        sh_words(&install_packages(p))
    );
    s.push_str(
        r#"mount_chroot
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
chroot "$ROOTFS" xbps-reconfigure -fa
"#,
    );
}

fn configure(s: &mut String, p: &Profile) {
    if p.overlay_dir.is_some() {
        let _ = writeln!(s, "info \"Copying overlay\"\ncp -a \"$HERE/{OVERLAY_DIR}/.\" \"$ROOTFS/\"");
    }
    s.push_str(
        r#"printf '%s\n' "$LIVE_HOSTNAME" > "$ROOTFS/etc/hostname"
ln -sf "/usr/share/zoneinfo/$LIVE_TIMEZONE" "$ROOTFS/etc/localtime"
if [ -f "$ROOTFS/etc/rc.conf" ]; then
	printf 'KEYMAP=%s\nTIMEZONE=%s\n' "$LIVE_KEYMAP" "$LIVE_TIMEZONE" >> "$ROOTFS/etc/rc.conf"
fi
printf 'LANG=%s\n' "$LIVE_LOCALE" > "$ROOTFS/etc/locale.conf"
if [ -f "$ROOTFS/etc/default/libc-locales" ]; then
	sed -i "s|^#[[:space:]]*\($LIVE_LOCALE[[:space:]]\)|\1|" "$ROOTFS/etc/default/libc-locales"
	chroot "$ROOTFS" xbps-reconfigure -f glibc-locales
fi
"#,
    );
    if p.init == Init::Dynamod {
        s.push_str(init::dynamod_rootfs_extra());
    }
    s.push_str(init::service_functions(p.init));
    for svc in enabled_services(p) {
        let _ = writeln!(s, "enable_service {}", sh_quote(&svc));
    }
    for svc in dedup(p.services.disable.clone()) {
        let _ = writeln!(s, "disable_service {}", sh_quote(&svc));
    }
    if p.post_rootfs_hook.is_some() {
        let _ = writeln!(
            s,
            "info \"Running post-rootfs hook\"\ninstall -Dm755 \"$HERE/{HOOK_PATH}\" \"$ROOTFS/tmp/vessel-post-rootfs.sh\"\n\
             chroot \"$ROOTFS\" /bin/sh /tmp/vessel-post-rootfs.sh\nrm -f \"$ROOTFS/tmp/vessel-post-rootfs.sh\""
        );
    }
}

fn iso(s: &mut String, active: &[(Bootloader, bool, bool)]) {
    let bios = active.iter().find(|(_, b, _)| *b).map(|(b, _, _)| *b);
    let uefi = active.iter().find(|(_, _, u)| *u).map(|(b, _, _)| *b);
    s.push_str("info \"Assembling $ISO\"\n");
    s.push_str("xorriso -as mkisofs -iso-level 3 -rock -joliet -joliet-long -volid \"$LABEL\" \\\n");
    if let Some(b) = bios {
        let _ = writeln!(s, "\t{} \\", bootloader::xorriso_bios_args(b));
    }
    if let Some(b) = uefi {
        if bios.is_some() {
            s.push_str("\t-eltorito-alt-boot \\\n");
        }
        let _ = writeln!(s, "\t{} -no-emul-boot -isohybrid-gpt-basdat \\", bootloader::xorriso_uefi_args(b));
    }
    s.push_str("\t-o \"$ISO\" \"$ISODIR\"\n");
    for (b, has_bios, _) in active {
        s.push_str(bootloader::post_iso(*b, *has_bios));
    }
    s.push_str(
        r#"(cd "$OUT" && sha256sum "$(basename "$ISO")" > "$(basename "$ISO").sha256")
info "Done: $ISO"
"#,
    );
}
