#!/bin/bash
# Generated by vessel from profile "void-gnome-dinit". Edit the profile in vessel, not this file.
#   init: dinit-chimera   userland: chimerautils
#   bootloaders: limine (BIOS+UEFI)
#   desktops: gnome   display manager: lightdm
# Run as root. WORK and OUT may be overridden from the environment.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="${WORK:-$HERE/work}"
ROOTFS="$WORK/rootfs"
ISODIR="$WORK/iso"
OUT="${OUT:-$HERE/out}"
ARCH='x86_64'
ISO_NAME='void-gnome-dinit'
LABEL='VOID_GNOME_DINIT'
MENU_TITLE='void-gnome-dinit'
LIVE_USER='anon'
LIVE_HOSTNAME='void-live'
LIVE_LOCALE='en_US.UTF-8'
LIVE_KEYMAP='us'
LIVE_TIMEZONE='UTC'
ISO="$OUT/void_gnome_dinit-$(date +%Y%m%d).iso"

info() { printf '==> %s\n' "$*"; }
warn() { printf '!! %s\n' "$*" >&2; }
die() { warn "$*"; exit 1; }

# A private /dev (tmpfs + nodes), not a bind of the host's: a package trigger
# recreating /dev/null through a bind mount corrupts the host's /dev/null.
mount_chroot() {
	mkdir -p "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/dev"
	mount --bind /proc "$ROOTFS/proc"
	mount --bind /sys "$ROOTFS/sys"
	mount -t tmpfs -o mode=755,nosuid tmpfs "$ROOTFS/dev"
	mkdir -p "$ROOTFS/dev/pts" "$ROOTFS/dev/shm"
	mknod -m 666 "$ROOTFS/dev/null" c 1 3
	mknod -m 666 "$ROOTFS/dev/zero" c 1 5
	mknod -m 666 "$ROOTFS/dev/full" c 1 7
	mknod -m 666 "$ROOTFS/dev/random" c 1 8
	mknod -m 666 "$ROOTFS/dev/urandom" c 1 9
	mknod -m 666 "$ROOTFS/dev/tty" c 5 0
	mknod -m 666 "$ROOTFS/dev/ptmx" c 5 2
	mount -t devpts -o gid=5,mode=620 devpts "$ROOTFS/dev/pts"
	mount -t tmpfs -o mode=1777 tmpfs "$ROOTFS/dev/shm"
}
umount_chroot() {
	local m
	for m in dev/shm dev/pts dev sys proc; do
		if mountpoint -q "$ROOTFS/$m" 2>/dev/null; then
			umount "$ROOTFS/$m" || umount -l "$ROOTFS/$m"
		fi
	done
	return 0
}
trap umount_chroot EXIT

# --- 1. preflight: host tools for the chosen init and bootloaders ---
[ "$(id -u)" -eq 0 ] || die "run as root (chroot, mounts, mknod)"
missing=0
need() { command -v "$1" >/dev/null 2>&1 || { warn "missing host tool $1 (xbps-install -S $2)"; missing=1; }; }
need_file() { [ -e "$1" ] || { warn "missing host file $1 (xbps-install -S $2)"; missing=1; }; }
need xbps-install xbps
need mksquashfs squashfs-tools
need xorriso xorriso
need mountpoint util-linux
need mkfs.ext3 e2fsprogs
need limine limine
need_file /usr/share/limine/limine-bios-cd.bin limine
need_file /usr/share/limine/BOOTX64.EFI limine
[ "$missing" -eq 0 ] || die "install the missing host packages and re-run"
free_gb=$(df --output=avail -BG "$HERE" | tail -1 | tr -dc 0-9)
[ "${free_gb:-0}" -ge 10 ] || die "need at least 10 GiB free under $HERE (have ${free_gb:-0} GiB)"

# --- 2. repositories: custom, then presets, then official ---
REPO_ARGS=(
	--repository='/voidlab/repo'
	--repository='https://repo-default.voidlinux.org/current'
)

# --- 3. rootfs: init dinit-chimera, userland chimerautils ---
case "$WORK" in
	"" | / | /home | /root | "$HERE") die "refusing to use WORK=$WORK as the scratch directory" ;;
esac
umount_chroot
if grep -qF " $WORK/" /proc/mounts; then
	die "something is still mounted under $WORK; unmount it before rebuilding"
fi
rm -rf "$WORK"
mkdir -p "$ROOTFS/var/db/xbps/keys" "$ROOTFS/etc/xbps.d" "$ISODIR/boot" "$OUT"
cp -a /var/db/xbps/keys/. "$ROOTFS/var/db/xbps/keys/"
cat > "$ROOTFS/etc/xbps.d/00-vessel.conf" <<'VESSEL_IGNORE'
ignorepkg=nano
VESSEL_IGNORE
info "Installing 26 packages into $ROOTFS"
XBPS_ARCH="$ARCH" xbps-install -S -y -r "$ROOTFS" -C "$ROOTFS/etc/xbps.d" "${REPO_ARGS[@]}" \
	'linux' 'base-system-dinit' 'dinit-chimera' 'dinit-void' 'dracut' 'binutils' 'xz' 'device-mapper' 'dhclient' 'dracut-network' 'openresolv' 'chimerautils' 'dbus' 'elogind' 'polkit' 'NetworkManager' 'xorg-minimal' 'xorg-fonts' 'mesa-dri' 'pipewire' 'wireplumber' 'xdg-user-dirs' 'gnome' 'lightdm' 'lightdm-gtk3-greeter' 'firefox'
mount_chroot
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
chroot "$ROOTFS" xbps-reconfigure -fa

# --- 4. configure: overlay, identity, services, hook ---
printf '%s\n' "$LIVE_HOSTNAME" > "$ROOTFS/etc/hostname"
ln -sf "/usr/share/zoneinfo/$LIVE_TIMEZONE" "$ROOTFS/etc/localtime"
if [ -f "$ROOTFS/etc/rc.conf" ]; then
	printf 'KEYMAP=%s\nTIMEZONE=%s\n' "$LIVE_KEYMAP" "$LIVE_TIMEZONE" >> "$ROOTFS/etc/rc.conf"
fi
printf 'LANG=%s\n' "$LIVE_LOCALE" > "$ROOTFS/etc/locale.conf"
if [ -f "$ROOTFS/etc/default/libc-locales" ]; then
	sed -i "s|^#[[:space:]]*\($LIVE_LOCALE[[:space:]]\)|\1|" "$ROOTFS/etc/default/libc-locales"
	chroot "$ROOTFS" xbps-reconfigure -f glibc-locales
fi
enable_service() {
	local d
	mkdir -p "$ROOTFS/etc/dinit.d/boot.d"
	for d in /etc/dinit.d /usr/lib/dinit.d; do
		if [ -e "$ROOTFS$d/$1" ]; then
			ln -sfn "$d/$1" "$ROOTFS/etc/dinit.d/boot.d/$1"
			return 0
		fi
	done
	warn "service $1 is not in the image (/etc/dinit.d or /usr/lib/dinit.d); skipped"
}
disable_service() {
	rm -f "$ROOTFS/etc/dinit.d/boot.d/$1"
}
enable_service 'agetty-tty1'
enable_service 'agetty-tty2'
enable_service 'dbus'
enable_service 'elogind'
enable_service 'NetworkManager'
enable_service 'lightdm'

# --- 5. kernel + initramfs: dracut + vmklive ---
KVER="$(ls "$ROOTFS/usr/lib/modules" | sort -V | tail -1)"
[ -n "$KVER" ] || die "no kernel installed in the rootfs"
cp "$ROOTFS/boot/vmlinuz-$KVER" "$ISODIR/boot/vmlinuz"
info "Building live initramfs (dracut + vmklive)"
rm -rf "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"
mkdir -p "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"
cp "$HERE/vmklive/"*.sh "$HERE/vmklive/"*.rules "$ROOTFS/usr/lib/dracut/modules.d/01vmklive/"
chroot "$ROOTFS" env -i PATH=/usr/bin:/usr/sbin \
	dracut -N --zstd --add-drivers ahci --force-add vmklive --omit systemd /boot/initrd "$KVER"
mv "$ROOTFS/boot/initrd" "$ISODIR/boot/initrd"
rm -rf "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"

# --- 6. squashfs: dmsquash-live layout ---
rm -f "$ROOTFS/etc/resolv.conf"
umount_chroot
info "Packing rootfs (dmsquash-live layout)"
rm -rf "$WORK/squash"
mkdir -p "$WORK/squash/LiveOS" "$ISODIR/LiveOS"
size_mb=$(du --apparent-size -sm "$ROOTFS" | cut -f1)
truncate -s "$((size_mb * 2 + 256))M" "$WORK/squash/LiveOS/rootfs.img"
mkfs.ext3 -q -F -m1 -d "$ROOTFS" "$WORK/squash/LiveOS/rootfs.img"
mksquashfs "$WORK/squash" "$ISODIR/LiveOS/squashfs.img" -comp zstd -noappend
rm -rf "$WORK/squash"

# --- 7. bootloaders: limine (BIOS+UEFI) ---
CMDLINE='root=live:CDLABEL=VOID_GNOME_DINIT ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=4 vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.user=anon noid.init_system=dinit'
CMDLINE_RAM='root=live:CDLABEL=VOID_GNOME_DINIT ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=4 vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.user=anon noid.init_system=dinit rd.live.ram'
info "Limine (BIOS + UEFI)"
mkdir -p "$ISODIR/boot/limine"
cp /usr/share/limine/limine-bios-cd.bin /usr/share/limine/limine-bios.sys "$ISODIR/boot/limine/"
cp /usr/share/limine/limine-uefi-cd.bin "$ISODIR/boot/limine/"
mkdir -p "$ISODIR/EFI/BOOT"
cp /usr/share/limine/BOOTX64.EFI "$ISODIR/EFI/BOOT/BOOTX64.EFI"
{
	echo "timeout: 5"
	echo
	echo "/$MENU_TITLE"
	echo "    protocol: linux"
	echo "    path: boot():/boot/vmlinuz"
	echo "    cmdline: $CMDLINE"
	echo "    module_path: boot():/boot/initrd"
	if [ -n "$CMDLINE_RAM" ]; then
		echo
		echo "/$MENU_TITLE (copy to RAM)"
		echo "    protocol: linux"
		echo "    path: boot():/boot/vmlinuz"
		echo "    cmdline: $CMDLINE_RAM"
		echo "    module_path: boot():/boot/initrd"
	fi
} > "$ISODIR/boot/limine/limine.conf"

# --- 8. iso: hybrid El Torito image ---
info "Assembling $ISO"
xorriso -as mkisofs -iso-level 3 -rock -joliet -joliet-long -volid "$LABEL" \
	-b boot/limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
	-eltorito-alt-boot \
	-e boot/limine/limine-uefi-cd.bin -no-emul-boot -isohybrid-gpt-basdat \
	-o "$ISO" "$ISODIR"
limine bios-install "$ISO"
(cd "$OUT" && sha256sum "$(basename "$ISO")" > "$(basename "$ISO").sha256")
info "Done: $ISO"
