#!/bin/bash
# Generated by vessel from profile "dynamod-cosmic". Edit the profile in vessel, not this file.
#   init: dynamod   userland: gnu
#   bootloaders: refind (UEFI), limine (BIOS)
#   desktops: cosmic   display manager: cosmic-greeter
# Run as root. WORK and OUT may be overridden from the environment.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="${WORK:-$HERE/work}"
if [ "${WORK#/}" = "$WORK" ]; then WORK="$PWD/$WORK"; fi
while [ "$WORK" != / ] && [ "${WORK%/}" != "$WORK" ]; do WORK="${WORK%/}"; done
ROOTFS="$WORK/rootfs"
ISODIR="$WORK/iso"
OUT="${OUT:-$HERE/out}"
ARCH='x86_64'
ISO_NAME='dynamod-cosmic'
LABEL='DYNAMOD_COSMIC'
MENU_TITLE='dynamod-cosmic'
LIVE_USER='anon'
LIVE_HOSTNAME='void-live'
LIVE_LOCALE='en_US.UTF-8'
LIVE_KEYMAP='us'
LIVE_TIMEZONE='UTC'
ISO="$OUT/dynamod_cosmic-$(date +%Y%m%d).iso"

info() { printf '==> %s\n' "$*"; }
warn() { printf '!! %s\n' "$*" >&2; }
die() { warn "$*"; exit 1; }

# A private /dev (tmpfs + nodes), not a bind of the host's: a package trigger
# recreating /dev/null through a bind mount corrupts the host's /dev/null.
mount_chroot() {
	mkdir -p "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/dev"
	mount --bind /proc "$ROOTFS/proc"
	mount --bind /sys "$ROOTFS/sys"
	mount -t tmpfs -o mode=755,nosuid tmpfs "$ROOTFS/dev"
	mkdir -p "$ROOTFS/dev/pts" "$ROOTFS/dev/shm"
	mknod -m 666 "$ROOTFS/dev/null" c 1 3
	mknod -m 666 "$ROOTFS/dev/zero" c 1 5
	mknod -m 666 "$ROOTFS/dev/full" c 1 7
	mknod -m 666 "$ROOTFS/dev/random" c 1 8
	mknod -m 666 "$ROOTFS/dev/urandom" c 1 9
	mknod -m 666 "$ROOTFS/dev/tty" c 5 0
	mknod -m 666 "$ROOTFS/dev/ptmx" c 5 2
	mount -t devpts -o gid=5,mode=620 devpts "$ROOTFS/dev/pts"
	mount -t tmpfs -o mode=1777 tmpfs "$ROOTFS/dev/shm"
}
umount_chroot() {
	local m
	for m in dev/shm dev/pts dev sys proc; do
		if mountpoint -q "$ROOTFS/$m" 2>/dev/null; then
			umount "$ROOTFS/$m" || umount -l "$ROOTFS/$m"
		fi
	done
	return 0
}
trap umount_chroot EXIT
make_efi_image() { # <image> <staging dir>
	local img="$1" dir="$2" size_kb
	size_kb=$(( $(du -sk "$dir" | cut -f1) * 11 / 10 + 2048 ))
	rm -f "$img"
	mkfs.vfat -C "$img" "$size_kb" >/dev/null
	mcopy -s -i "$img" "$dir"/* ::/
}

# --- 1. preflight: host tools for the chosen init and bootloaders ---
[ "$(id -u)" -eq 0 ] || die "run as root (chroot, mounts, mknod)"
missing=0
need() { command -v "$1" >/dev/null 2>&1 || { warn "missing host tool $1 (xbps-install -S $2)"; missing=1; }; }
need_file() { [ -e "$1" ] || { warn "missing host file $1 (xbps-install -S $2)"; missing=1; }; }
need xbps-install xbps
need mksquashfs squashfs-tools
need xorriso xorriso
need mountpoint util-linux
need readelf binutils
need cpio cpio
need gzip gzip
need modprobe kmod
need depmod kmod
need mkfs.vfat dosfstools
need mcopy mtools
need limine limine
need_file /usr/share/refind/refind_x64.efi refind
need_file /usr/share/limine/limine-bios-cd.bin limine
[ "$missing" -eq 0 ] || die "install the missing host packages and re-run"
free_dir="$WORK"
while [ ! -d "$free_dir" ]; do free_dir="$(dirname "$free_dir")"; done
free_gb=$(df --output=avail -BG "$free_dir" | tail -1 | tr -dc 0-9)
[ "${free_gb:-0}" -ge 10 ] || die "need at least 10 GiB free under $free_dir (have ${free_gb:-0} GiB)"

# --- 2. repositories: custom, then presets, then official ---
REPO_ARGS=(
	--repository='/voidlab/repo'
	--repository='https://repo-default.voidlinux.org/current'
)

# --- 3. rootfs: init dynamod, userland gnu ---
case "$WORK" in
	"" | / | /home | /root | "$HERE") die "refusing to use WORK=$WORK as the scratch directory" ;;
esac
# Only ever wipe a folder this script created (marked with .vessel-work).
if [ -d "$WORK" ] && [ ! -e "$WORK/.vessel-work" ] && [ -n "$(ls -A "$WORK")" ]; then
	die "refusing to wipe $WORK: not a vessel scratch folder (no .vessel-work); remove it yourself or set WORK elsewhere"
fi
umount_chroot
if awk -v w="$WORK" '$2 == w || index($2, w "/") == 1 { found = 1 } END { exit !found }' /proc/mounts; then
	die "something is still mounted under $WORK; unmount it before rebuilding"
fi
rm -rf "$WORK"
mkdir -p "$ROOTFS/var/db/xbps/keys" "$ROOTFS/etc/xbps.d" "$ISODIR/boot" "$OUT"
touch "$WORK/.vessel-work"
cp -a /var/db/xbps/keys/. "$ROOTFS/var/db/xbps/keys/"
cat > "$ROOTFS/etc/xbps.d/00-vessel.conf" <<'VESSEL_IGNORE'
ignorepkg=runit-void
VESSEL_IGNORE
info "Installing 18 packages into $ROOTFS"
XBPS_ARCH="$ARCH" xbps-install -S -y -I -r "$ROOTFS" -C "$ROOTFS/etc/xbps.d" "${REPO_ARGS[@]}" \
	'linux' 'base-system' 'dynamod' 'zstd' 'kmod' 'util-linux' 'dbus' 'elogind' 'polkit' 'NetworkManager' 'xorg-minimal' 'xorg-fonts' 'mesa-dri' 'pipewire' 'wireplumber' 'xdg-user-dirs' 'cosmic-desktop' 'cosmic-greeter'
mount_chroot
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
chroot "$ROOTFS" xbps-reconfigure -fa

# --- 4. configure: overlay, identity, services, hook ---
info "Copying overlay"
cp -a "$HERE/overlay/." "$ROOTFS/"
printf '%s\n' "$LIVE_HOSTNAME" > "$ROOTFS/etc/hostname"
ln -sf "/usr/share/zoneinfo/$LIVE_TIMEZONE" "$ROOTFS/etc/localtime"
if [ -f "$ROOTFS/etc/rc.conf" ]; then
	printf 'KEYMAP=%s\nTIMEZONE=%s\n' "$LIVE_KEYMAP" "$LIVE_TIMEZONE" >> "$ROOTFS/etc/rc.conf"
fi
printf 'LANG=%s\n' "$LIVE_LOCALE" > "$ROOTFS/etc/locale.conf"
if [ -f "$ROOTFS/etc/default/libc-locales" ]; then
	sed -i "s|^#[[:space:]]*\($LIVE_LOCALE[[:space:]]\)|\1|" "$ROOTFS/etc/default/libc-locales"
	chroot "$ROOTFS" xbps-reconfigure -f glibc-locales
fi
info "dynamod: permissive D-Bus system policy (Void's default blocks the mimic daemons)"
mkdir -p "$ROOTFS/etc/dbus-1"
cat > "$ROOTFS/etc/dbus-1/system.conf" <<'DBUSCONF'
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
  "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
  <type>system</type>
  <listen>unix:path=/run/dbus/system_bus_socket</listen>
  <auth>EXTERNAL</auth>
  <policy context="default">
    <allow send_destination="*" eavesdrop="true"/>
    <allow eavesdrop="true"/>
    <allow own="*"/>
    <allow send_type="method_call"/>
    <allow send_type="signal"/>
  </policy>
  <includedir>system.d</includedir>
  <includedir>/usr/share/dbus-1/system.d</includedir>
</busconfig>
DBUSCONF
info "dynamod: creating passwordless live user $LIVE_USER"
chroot "$ROOTFS" useradd -m -G wheel,audio,video,input -s /bin/bash "$LIVE_USER"
chroot "$ROOTFS" passwd -d "$LIVE_USER"
enable_service() {
	local f="$ROOTFS/etc/dynamod/services/$1.toml"
	local avail="$ROOTFS/usr/share/dynamod/desktop-services/$1.toml"
	if [ -e "$f" ]; then
		return 0
	elif [ -e "$avail" ]; then
		cp "$avail" "$f"
	else
		warn "service $1 has no dynamod definition ($1.toml); skipped"
	fi
}
disable_service() {
	rm -f "$ROOTFS/etc/dynamod/services/$1.toml"
}
enable_service 'dbus'
enable_service 'elogind'
enable_service 'NetworkManager'
enable_service 'cosmic-greeter'
info "Running post-rootfs hook"
install -Dm755 "$HERE/hooks/post_rootfs.sh" "$ROOTFS/tmp/vessel-post-rootfs.sh"
chroot "$ROOTFS" /bin/sh /tmp/vessel-post-rootfs.sh
rm -f "$ROOTFS/tmp/vessel-post-rootfs.sh"

# --- 5. kernel + initramfs: dynamod-init ---
KVER="$(ls "$ROOTFS/usr/lib/modules" | sort -V | tail -1)"
[ -n "$KVER" ] || die "no kernel installed in the rootfs"
cp "$ROOTFS/boot/vmlinuz-$KVER" "$ISODIR/boot/vmlinuz"
info "Building dynamod initramfs"
bash "$HERE/dynamod-initramfs.sh" "$ROOTFS" "$KVER" "$ISODIR/boot/initrd"

# --- 6. squashfs: dynamod live layout ---
rm -f "$ROOTFS/etc/resolv.conf"
umount_chroot
info "Packing rootfs (dynamod live layout)"
mkdir -p "$ISODIR/live"
mksquashfs "$ROOTFS" "$ISODIR/live/root.squashfs" -comp xz -noappend

# --- 7. bootloaders: refind (UEFI), limine (BIOS) ---
CMDLINE='rdinit=/sbin/dynamod-init dynamod.live=1 dynamod.media=LABEL=DYNAMOD_COSMIC dynamod.squashfs=/live/root.squashfs rootwait'
CMDLINE_RAM=''
info "rEFInd (UEFI)"
rm -rf "$WORK/efi-refind"
mkdir -p "$WORK/efi-refind/EFI/BOOT" "$WORK/efi-refind/boot" "$ISODIR/boot/refind"
cp /usr/share/refind/refind_x64.efi "$WORK/efi-refind/EFI/BOOT/BOOTX64.EFI"
cp "$ISODIR/boot/vmlinuz" "$ISODIR/boot/initrd" "$WORK/efi-refind/boot/"
{
	echo "timeout 5"
	echo "scanfor manual"
	echo "menuentry \"$MENU_TITLE\" {"
	echo "	loader /boot/vmlinuz"
	echo "	initrd /boot/initrd"
	echo "	options \"$CMDLINE\""
	echo "}"
} > "$WORK/efi-refind/EFI/BOOT/refind.conf"
make_efi_image "$ISODIR/boot/refind/efiboot.img" "$WORK/efi-refind"
info "Limine (BIOS)"
mkdir -p "$ISODIR/boot/limine"
cp /usr/share/limine/limine-bios-cd.bin /usr/share/limine/limine-bios.sys "$ISODIR/boot/limine/"
{
	echo "timeout: 5"
	echo
	echo "/$MENU_TITLE"
	echo "    protocol: linux"
	echo "    path: boot():/boot/vmlinuz"
	echo "    cmdline: $CMDLINE"
	echo "    module_path: boot():/boot/initrd"
	if [ -n "$CMDLINE_RAM" ]; then
		echo
		echo "/$MENU_TITLE (copy to RAM)"
		echo "    protocol: linux"
		echo "    path: boot():/boot/vmlinuz"
		echo "    cmdline: $CMDLINE_RAM"
		echo "    module_path: boot():/boot/initrd"
	fi
} > "$ISODIR/boot/limine/limine.conf"

# --- 8. iso: hybrid El Torito image ---
info "Assembling $ISO"
xorriso -as mkisofs -iso-level 3 -rock -joliet -joliet-long -volid "$LABEL" \
	-b boot/limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
	-eltorito-alt-boot \
	-e boot/refind/efiboot.img -no-emul-boot -isohybrid-gpt-basdat \
	-o "$ISO" "$ISODIR"
limine bios-install "$ISO"
(cd "$OUT" && sha256sum "$(basename "$ISO")" > "$(basename "$ISO").sha256")
info "Done: $ISO"
