#!/bin/bash
# Generated by vessel from profile "void-live". Edit the profile in vessel, not this file.
#   init: runit   userland: gnu
#   bootloaders: grub (BIOS+UEFI)
#   desktops: none (console)   display manager: none
# Run as root. WORK and OUT may be overridden from the environment.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="${WORK:-$HERE/work}"
if [ "${WORK#/}" = "$WORK" ]; then WORK="$PWD/$WORK"; fi
while [ "$WORK" != / ] && [ "${WORK%/}" != "$WORK" ]; do WORK="${WORK%/}"; done
ROOTFS="$WORK/rootfs"
ISODIR="$WORK/iso"
OUT="${OUT:-$HERE/out}"
ARCH='x86_64'
ISO_NAME='void-live'
LABEL='VOID_LIVE'
MENU_TITLE='void-live'
LIVE_USER='anon'
LIVE_HOSTNAME='void-live'
LIVE_LOCALE='en_US.UTF-8'
LIVE_KEYMAP='us'
LIVE_TIMEZONE='UTC'
ISO="$OUT/void_live-$(date +%Y%m%d).iso"

info() { printf '==> %s\n' "$*"; }
warn() { printf '!! %s\n' "$*" >&2; }
die() { warn "$*"; exit 1; }

# A private /dev (tmpfs + nodes), not a bind of the host's: a package trigger
# recreating /dev/null through a bind mount corrupts the host's /dev/null.
mount_chroot() {
	mkdir -p "$ROOTFS/proc" "$ROOTFS/sys" "$ROOTFS/dev"
	mount --bind /proc "$ROOTFS/proc"
	mount --bind /sys "$ROOTFS/sys"
	mount -t tmpfs -o mode=755,nosuid tmpfs "$ROOTFS/dev"
	mkdir -p "$ROOTFS/dev/pts" "$ROOTFS/dev/shm"
	mknod -m 666 "$ROOTFS/dev/null" c 1 3
	mknod -m 666 "$ROOTFS/dev/zero" c 1 5
	mknod -m 666 "$ROOTFS/dev/full" c 1 7
	mknod -m 666 "$ROOTFS/dev/random" c 1 8
	mknod -m 666 "$ROOTFS/dev/urandom" c 1 9
	mknod -m 666 "$ROOTFS/dev/tty" c 5 0
	mknod -m 666 "$ROOTFS/dev/ptmx" c 5 2
	mount -t devpts -o gid=5,mode=620 devpts "$ROOTFS/dev/pts"
	mount -t tmpfs -o mode=1777 tmpfs "$ROOTFS/dev/shm"
}
umount_chroot() {
	local m
	for m in dev/shm dev/pts dev sys proc; do
		if mountpoint -q "$ROOTFS/$m" 2>/dev/null; then
			umount "$ROOTFS/$m" || umount -l "$ROOTFS/$m"
		fi
	done
	return 0
}
trap umount_chroot EXIT
make_efi_image() { # <image> <staging dir>
	local img="$1" dir="$2" size_kb
	size_kb=$(( $(du -sk "$dir" | cut -f1) * 11 / 10 + 2048 ))
	rm -f "$img"
	mkfs.vfat -C "$img" "$size_kb" >/dev/null
	mcopy -s -i "$img" "$dir"/* ::/
}

# --- 1. preflight: host tools for the chosen init and bootloaders ---
[ "$(id -u)" -eq 0 ] || die "run as root (chroot, mounts, mknod)"
missing=0
need() { command -v "$1" >/dev/null 2>&1 || { warn "missing host tool $1 (xbps-install -S $2)"; missing=1; }; }
need_file() { [ -e "$1" ] || { warn "missing host file $1 (xbps-install -S $2)"; missing=1; }; }
need xbps-install xbps
need mksquashfs squashfs-tools
need xorriso xorriso
need mountpoint util-linux
need mkfs.ext3 e2fsprogs
need grub-mkimage grub
need grub-mkstandalone grub-x86_64-efi
need mkfs.vfat dosfstools
need mcopy mtools
need_file /usr/lib/grub/i386-pc/boot_hybrid.img grub
[ "$missing" -eq 0 ] || die "install the missing host packages and re-run"
free_dir="$WORK"
while [ ! -d "$free_dir" ]; do free_dir="$(dirname "$free_dir")"; done
free_gb=$(df --output=avail -BG "$free_dir" | tail -1 | tr -dc 0-9)
[ "${free_gb:-0}" -ge 10 ] || die "need at least 10 GiB free under $free_dir (have ${free_gb:-0} GiB)"

# --- 2. repositories: custom, then presets, then official ---
REPO_ARGS=(
	--repository='https://repo-default.voidlinux.org/current'
)

# --- 3. rootfs: init runit, userland gnu ---
case "$WORK" in
	"" | / | /home | /root | "$HERE") die "refusing to use WORK=$WORK as the scratch directory" ;;
esac
# Only ever wipe a folder this script created (marked with .vessel-work).
if [ -d "$WORK" ] && [ ! -e "$WORK/.vessel-work" ] && [ -n "$(ls -A "$WORK")" ]; then
	die "refusing to wipe $WORK: not a vessel scratch folder (no .vessel-work); remove it yourself or set WORK elsewhere"
fi
umount_chroot
if awk -v w="$WORK" '$2 == w || index($2, w "/") == 1 { found = 1 } END { exit !found }' /proc/mounts; then
	die "something is still mounted under $WORK; unmount it before rebuilding"
fi
rm -rf "$WORK"
mkdir -p "$ROOTFS/var/db/xbps/keys" "$ROOTFS/etc/xbps.d" "$ISODIR/boot" "$OUT"
touch "$WORK/.vessel-work"
cp -a /var/db/xbps/keys/. "$ROOTFS/var/db/xbps/keys/"
info "Installing 9 packages into $ROOTFS"
XBPS_ARCH="$ARCH" xbps-install -S -y -r "$ROOTFS" -C "$ROOTFS/etc/xbps.d" "${REPO_ARGS[@]}" \
	'linux' 'base-system' 'dracut' 'binutils' 'xz' 'device-mapper' 'dhclient' 'dracut-network' 'openresolv'
mount_chroot
cp /etc/resolv.conf "$ROOTFS/etc/resolv.conf"
chroot "$ROOTFS" xbps-reconfigure -fa

# --- 4. configure: overlay, identity, services, hook ---
printf '%s\n' "$LIVE_HOSTNAME" > "$ROOTFS/etc/hostname"
ln -sf "/usr/share/zoneinfo/$LIVE_TIMEZONE" "$ROOTFS/etc/localtime"
if [ -f "$ROOTFS/etc/rc.conf" ]; then
	printf 'KEYMAP=%s\nTIMEZONE=%s\n' "$LIVE_KEYMAP" "$LIVE_TIMEZONE" >> "$ROOTFS/etc/rc.conf"
fi
printf 'LANG=%s\n' "$LIVE_LOCALE" > "$ROOTFS/etc/locale.conf"
if [ -f "$ROOTFS/etc/default/libc-locales" ]; then
	sed -i "s|^#[[:space:]]*\($LIVE_LOCALE[[:space:]]\)|\1|" "$ROOTFS/etc/default/libc-locales"
	chroot "$ROOTFS" xbps-reconfigure -f glibc-locales
fi
enable_service() {
	if [ -d "$ROOTFS/etc/sv/$1" ]; then
		ln -sfn "/etc/sv/$1" "$ROOTFS/etc/runit/runsvdir/default/$1"
	else
		warn "service $1 is not in the image (/etc/sv/$1); skipped"
	fi
}
disable_service() {
	rm -f "$ROOTFS/etc/runit/runsvdir/default/$1"
}
enable_service 'agetty-tty1'
enable_service 'agetty-tty2'

# --- 5. kernel + initramfs: dracut + vmklive ---
KVER="$(ls "$ROOTFS/usr/lib/modules" | sort -V | tail -1)"
[ -n "$KVER" ] || die "no kernel installed in the rootfs"
cp "$ROOTFS/boot/vmlinuz-$KVER" "$ISODIR/boot/vmlinuz"
info "Building live initramfs (dracut + vmklive)"
rm -rf "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"
mkdir -p "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"
cp "$HERE/vmklive/"*.sh "$HERE/vmklive/"*.rules "$ROOTFS/usr/lib/dracut/modules.d/01vmklive/"
chroot "$ROOTFS" env -i PATH=/usr/bin:/usr/sbin \
	dracut -N --zstd --add-drivers ahci --force-add vmklive --omit systemd /boot/initrd "$KVER"
mv "$ROOTFS/boot/initrd" "$ISODIR/boot/initrd"
rm -rf "$ROOTFS/usr/lib/dracut/modules.d/01vmklive"

# --- 6. squashfs: dmsquash-live layout ---
rm -f "$ROOTFS/etc/resolv.conf"
umount_chroot
info "Packing rootfs (dmsquash-live layout)"
rm -rf "$WORK/squash"
mkdir -p "$WORK/squash/LiveOS" "$ISODIR/LiveOS"
size_mb=$(du --apparent-size -sm "$ROOTFS" | cut -f1)
truncate -s "$((size_mb * 2 + 256))M" "$WORK/squash/LiveOS/rootfs.img"
mkfs.ext3 -q -F -m1 -d "$ROOTFS" "$WORK/squash/LiveOS/rootfs.img"
mksquashfs "$WORK/squash" "$ISODIR/LiveOS/squashfs.img" -comp zstd -noappend
rm -rf "$WORK/squash"

# --- 7. bootloaders: grub (BIOS+UEFI) ---
CMDLINE='root=live:CDLABEL=VOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=4 vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.user=anon'
CMDLINE_RAM='root=live:CDLABEL=VOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=4 vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.user=anon rd.live.ram'
info "GRUB (BIOS + UEFI)"
mkdir -p "$ISODIR/boot/grub"
{
	echo "set timeout=5"
	echo "set default=0"
	echo "search --no-floppy --label --set=root $LABEL"
	echo "menuentry \"$MENU_TITLE\" {"
	echo "	linux /boot/vmlinuz $CMDLINE"
	echo "	initrd /boot/initrd"
	echo "}"
	if [ -n "$CMDLINE_RAM" ]; then
		echo "menuentry \"$MENU_TITLE (copy to RAM)\" {"
		echo "	linux /boot/vmlinuz $CMDLINE_RAM"
		echo "	initrd /boot/initrd"
		echo "}"
	fi
} > "$ISODIR/boot/grub/grub.cfg"
mkdir -p "$ISODIR/boot/grub/i386-pc"
cp /usr/lib/grub/i386-pc/*.mod /usr/lib/grub/i386-pc/*.lst "$ISODIR/boot/grub/i386-pc/"
grub-mkimage -O i386-pc-eltorito -p /boot/grub -o "$ISODIR/boot/grub/i386-pc/eltorito.img" \
	biosdisk iso9660 part_msdos part_gpt normal linux search search_label configfile echo
rm -rf "$WORK/efi-grub"
mkdir -p "$WORK/efi-grub/EFI/BOOT"
grub-mkstandalone -O x86_64-efi -o "$WORK/efi-grub/EFI/BOOT/BOOTX64.EFI" \
	"boot/grub/grub.cfg=$ISODIR/boot/grub/grub.cfg"
make_efi_image "$ISODIR/boot/grub/efiboot.img" "$WORK/efi-grub"

# --- 8. iso: hybrid El Torito image ---
info "Assembling $ISO"
xorriso -as mkisofs -iso-level 3 -rock -joliet -joliet-long -volid "$LABEL" \
	-b boot/grub/i386-pc/eltorito.img -no-emul-boot -boot-load-size 4 -boot-info-table --grub2-boot-info --grub2-mbr /usr/lib/grub/i386-pc/boot_hybrid.img \
	-eltorito-alt-boot \
	-e boot/grub/efiboot.img -no-emul-boot -isohybrid-gpt-basdat \
	-o "$ISO" "$ISODIR"
(cd "$OUT" && sha256sum "$(basename "$ISO")" > "$(basename "$ISO").sha256")
info "Done: $ISO"
